using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AthamePlugin.Tidal
{
    public class Country
    {
        public string Name { get; set; }
        public string Code { get; set; }

        public Country(string name, string code)
        {
            Name = name;
            Code = code;
        }

        public override string ToString()
        {
            return $"{Name} [{Code}]";
        }

        public static Country[] AllCountries = {
            new Country ("Afghanistan","AF"),
            new Country ("Albania","AL"),
            new Country ("Algeria","DZ"),
            new Country ("Andorra","AD"),
            new Country ("Angola","AO"),
            new Country ("Antigua and Barbuda","AG"),
            new Country ("Argentina","AR"),
            new Country ("Armenia","AM"),
            new Country ("Australia","AU"),
            new Country ("Austria","AT"),
            new Country ("Azerbaijan","AZ"),
            new Country ("Bahamas, The","BS"),
            new Country ("Bahrain","BH"),
            new Country ("Bangladesh","BD"),
            new Country ("Barbados","BB"),
            new Country ("Belarus","BY"),
            new Country ("Belgium","BE"),
            new Country ("Belize","BZ"),
            new Country ("Benin","BJ"),
            new Country ("Bhutan","BT"),
            new Country ("Bolivia","BO"),
            new Country ("Bosnia and Herzegovina","BA"),
            new Country ("Botswana","BW"),
            new Country ("Brazil","BR"),
            new Country ("Brunei","BN"),
            new Country ("Bulgaria","BG"),
            new Country ("Burkina Faso","BF"),
            new Country ("Burundi","BI"),
            new Country ("Cambodia","KH"),
            new Country ("Cameroon","CM"),
            new Country ("Canada","CA"),
            new Country ("Cape Verde","CV"),
            new Country ("Central African Republic","CF"),
            new Country ("Chad","TD"),
            new Country ("Chile","CL"),
            new Country ("China, People's Republic of","CN"),
            new Country ("Colombia","CO"),
            new Country ("Comoros","KM"),
            new Country ("Congo, (Congo  Kinshasa)","CD"),
            new Country ("Congo, (Congo  Brazzaville)","CG"),
            new Country ("Costa Rica","CR"),
            new Country ("Cote d'Ivoire (Ivory Coast)","CI"),
            new Country ("Croatia","HR"),
            new Country ("Cuba","CU"),
            new Country ("Cyprus","CY"),
            new Country ("Czech Republic","CZ"),
            new Country ("Denmark","DK"),
            new Country ("Djibouti","DJ"),
            new Country ("Dominica","DM"),
            new Country ("Dominican Republic","DO"),
            new Country ("Ecuador","EC"),
            new Country ("Egypt","EG"),
            new Country ("El Salvador","SV"),
            new Country ("Equatorial Guinea","GQ"),
            new Country ("Eritrea","ER"),
            new Country ("Estonia","EE"),
            new Country ("Ethiopia","ET"),
            new Country ("Fiji","FJ"),
            new Country ("Finland","FI"),
            new Country ("France","FR"),
            new Country ("Gabon","GA"),
            new Country ("Gambia, The","GM"),
            new Country ("Georgia","GE"),
            new Country ("Germany","DE"),
            new Country ("Ghana","GH"),
            new Country ("Greece","GR"),
            new Country ("Grenada","GD"),
            new Country ("Guatemala","GT"),
            new Country ("Guinea","GN"),
            new Country ("Guinea-Bissau","GW"),
            new Country ("Guyana","GY"),
            new Country ("Haiti","HT"),
            new Country ("Honduras","HN"),
            new Country ("Hungary","HU"),
            new Country ("Iceland","IS"),
            new Country ("India","IN"),
            new Country ("Indonesia","ID"),
            new Country ("Iran","IR"),
            new Country ("Iraq","IQ"),
            new Country ("Ireland","IE"),
            new Country ("Israel","IL"),
            new Country ("Italy","IT"),
            new Country ("Jamaica","JM"),
            new Country ("Japan","JP"),
            new Country ("Jordan","JO"),
            new Country ("Kazakhstan","KZ"),
            new Country ("Kenya","KE"),
            new Country ("Kiribati","KI"),
            new Country ("Korea, North","KP"),
            new Country ("Korea, South","KR"),
            new Country ("Kuwait","KW"),
            new Country ("Kyrgyzstan","KG"),
            new Country ("Laos","LA"),
            new Country ("Latvia","LV"),
            new Country ("Lebanon","LB"),
            new Country ("Lesotho","LS"),
            new Country ("Liberia","LR"),
            new Country ("Libya","LY"),
            new Country ("Liechtenstein","LI"),
            new Country ("Lithuania","LT"),
            new Country ("Luxembourg","LU"),
            new Country ("Macedonia","MK"),
            new Country ("Madagascar","MG"),
            new Country ("Malawi","MW"),
            new Country ("Malaysia","MY"),
            new Country ("Maldives","MV"),
            new Country ("Mali","ML"),
            new Country ("Malta","MT"),
            new Country ("Marshall Islands","MH"),
            new Country ("Mauritania","MR"),
            new Country ("Mauritius","MU"),
            new Country ("Mexico","MX"),
            new Country ("Micronesia","FM"),
            new Country ("Moldova","MD"),
            new Country ("Monaco","MC"),
            new Country ("Mongolia","MN"),
            new Country ("Montenegro","ME"),
            new Country ("Morocco","MA"),
            new Country ("Mozambique","MZ"),
            new Country ("Myanmar (Burma)","MM"),
            new Country ("Namibia","NA"),
            new Country ("Nauru","NR"),
            new Country ("Nepal","NP"),
            new Country ("Netherlands","NL"),
            new Country ("New Zealand","NZ"),
            new Country ("Nicaragua","NI"),
            new Country ("Niger","NE"),
            new Country ("Nigeria","NG"),
            new Country ("Norway","NO"),
            new Country ("Oman","OM"),
            new Country ("Pakistan","PK"),
            new Country ("Palau","PW"),
            new Country ("Panama","PA"),
            new Country ("Papua New Guinea","PG"),
            new Country ("Paraguay","PY"),
            new Country ("Peru","PE"),
            new Country ("Philippines","PH"),
            new Country ("Poland","PL"),
            new Country ("Portugal","PT"),
            new Country ("Qatar","QA"),
            new Country ("Romania","RO"),
            new Country ("Russia","RU"),
            new Country ("Rwanda","RW"),
            new Country ("Saint Kitts and Nevis","KN"),
            new Country ("Saint Lucia","LC"),
            new Country ("Saint Vincent and the Grenadines","VC"),
            new Country ("Samoa","WS"),
            new Country ("San Marino","SM"),
            new Country ("Sao Tome and Principe","ST"),
            new Country ("Saudi Arabia","SA"),
            new Country ("Senegal","SN"),
            new Country ("Serbia","RS"),
            new Country ("Seychelles","SC"),
            new Country ("Sierra Leone","SL"),
            new Country ("Singapore","SG"),
            new Country ("Slovakia","SK"),
            new Country ("Slovenia","SI"),
            new Country ("Solomon Islands","SB"),
            new Country ("Somalia","SO"),
            new Country ("South Africa","ZA"),
            new Country ("Spain","ES"),
            new Country ("Sri Lanka","LK"),
            new Country ("Sudan","SD"),
            new Country ("Suriname","SR"),
            new Country ("Swaziland","SZ"),
            new Country ("Sweden","SE"),
            new Country ("Switzerland","CH"),
            new Country ("Syria","SY"),
            new Country ("Tajikistan","TJ"),
            new Country ("Tanzania","TZ"),
            new Country ("Thailand","TH"),
            new Country ("Timor-Leste (East Timor)","TL"),
            new Country ("Togo","TG"),
            new Country ("Tonga","TO"),
            new Country ("Trinidad and Tobago","TT"),
            new Country ("Tunisia","TN"),
            new Country ("Turkey","TR"),
            new Country ("Turkmenistan","TM"),
            new Country ("Tuvalu","TV"),
            new Country ("Uganda","UG"),
            new Country ("Ukraine","UA"),
            new Country ("United Arab Emirates","AE"),
            new Country ("United Kingdom","GB"),
            new Country ("United States","US"),
            new Country ("Uruguay","UY"),
            new Country ("Uzbekistan","UZ"),
            new Country ("Vanuatu","VU"),
            new Country ("Vatican City","VA"),
            new Country ("Venezuela","VE"),
            new Country ("Vietnam","VN"),
            new Country ("Yemen","YE"),
            new Country ("Zambia","ZM"),
            new Country ("Zimbabwe","ZW"),
            new Country ("Abkhazia","GE"),
            new Country ("China, Republic of (Taiwan)","TW"),
            new Country ("Nagorno-Karabakh","AZ"),
            new Country ("Northern Cyprus","CY"),
            new Country ("Pridnestrovie (Transnistria)","MD"),
            new Country ("Somaliland","SO"),
            new Country ("South Ossetia","GE"),
            new Country ("Ashmore and Cartier Islands","AU"),
            new Country ("Christmas Island","CX"),
            new Country ("Cocos (Keeling) Islands","CC"),
            new Country ("Coral Sea Islands","AU"),
            new Country ("Heard Island and McDonald Islands","HM"),
            new Country ("Norfolk Island","NF"),
            new Country ("New Caledonia","NC"),
            new Country ("French Polynesia","PF"),
            new Country ("Mayotte","YT"),
            new Country ("Saint Barthelemy","GP"),
            new Country ("Saint Martin","GP"),
            new Country ("Saint Pierre and Miquelon","PM"),
            new Country ("Wallis and Futuna","WF"),
            new Country ("French Southern and Antarctic Lands","TF"),
            new Country ("Clipperton Island","PF"),
            new Country ("Bouvet Island","BV"),
            new Country ("Cook Islands","CK"),
            new Country ("Niue","NU"),
            new Country ("Tokelau","TK"),
            new Country ("Guernsey","GG"),
            new Country ("Isle of Man","IM"),
            new Country ("Jersey","JE"),
            new Country ("Anguilla","AI"),
            new Country ("Bermuda","BM"),
            new Country ("British Indian Ocean Territory","IO"),
            new Country ("British Virgin Islands","VG"),
            new Country ("Cayman Islands","KY"),
            new Country ("Falkland Islands (Islas Malvinas)","FK"),
            new Country ("Gibraltar","GI"),
            new Country ("Montserrat","MS"),
            new Country ("Pitcairn Islands","PN"),
            new Country ("Saint Helena","SH"),
            new Country ("South Georgia & South Sandwich Islands","GS"),
            new Country ("Turks and Caicos Islands","TC"),
            new Country ("Northern Mariana Islands","MP"),
            new Country ("Puerto Rico","PR"),
            new Country ("American Samoa","AS"),
            new Country ("Baker Island","UM"),
            new Country ("Guam","GU"),
            new Country ("Howland Island","UM"),
            new Country ("Jarvis Island","UM"),
            new Country ("Johnston Atoll","UM"),
            new Country ("Kingman Reef","UM"),
            new Country ("Midway Islands","UM"),
            new Country ("Navassa Island","UM"),
            new Country ("Palmyra Atoll","UM"),
            new Country ("U.S. Virgin Islands","VI"),
            new Country ("Wake Island","UM"),
            new Country ("Hong Kong","HK"),
            new Country ("Macau","MO"),
            new Country ("Faroe Islands","FO"),
            new Country ("Greenland","GL"),
            new Country ("French Guiana","GF"),
            new Country ("Guadeloupe","GP"),
            new Country ("Martinique","MQ"),
            new Country ("Reunion","RE"),
            new Country ("Aland","AX"),
            new Country ("Aruba","AW"),
            new Country ("Netherlands Antilles","AN"),
            new Country ("Svalbard","SJ"),
            new Country ("Ascension","AC"),
            new Country ("Tristan da Cunha","TA"),
            new Country ("Australian Antarctic Territory","AQ"),
            new Country ("Ross Dependency","AQ"),
            new Country ("Peter I Island","AQ"),
            new Country ("Queen Maud Land","AQ"),
            new Country ("British Antarctic Territory","AQ")
        };
    }
}
